services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/api/app       # monta solo la carpeta app con tu código Python
      - ./alembic:/api/alembic # monta la carpeta de migraciones
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["/api/.venv/bin/uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    develop:
      watch:
        - action: sync
          path: .
          target: /api
          ignore:
            - .venv/
            - __pycache__/
        - action: rebuild
          path: ./pyproject.toml

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
